import type { PipelineStage } from "@/lib/types";

export const ORGANIZATION_NAME = "Triangle Services";

export const COMPANY_TYPES = [
  "epc_contractor",
  "mep_contractor",
  "electrical_contractor",
  "hvac_contractor",
  "data_center_contractor",
  "rail_oem",
  "industrial_oem",
  "general_contractor",
  "engineering_company",
  "staffing_partner",
  "headhunter",
  "panel_builder",
  "automation_integrator",
  "steel_industry_supplier",
  "other",
];

export const SECTORS = [
  "Data center",
  "Rail / rolling stock",
  "HVAC",
  "MEP",
  "Industrial construction",
  "Steel / metals",
  "Automation",
  "Electrical installation",
  "Commissioning",
  "Manufacturing",
  "Energy",
  "Infrastructure",
];

export const COUNTRIES = [
  "Austria",
  "Germany",
  "Croatia",
  "Slovenia",
  "Hungary",
  "Czech Republic",
  "Slovakia",
  "Netherlands",
  "Denmark",
  "Sweden",
  "Switzerland",
  "Italy",
];

export const OFFER_TYPES = [
  "Electrical installation crew",
  "Cable pulling crew",
  "Cable tray installation crew",
  "Rail retrofit electrical crew",
  "Industrial installation team",
  "HVAC/MEP electrical support",
  "Data-center electrical support",
  "PLC commissioning engineer",
  "Automation engineer",
  "Electrical supervisor",
  "Site manager",
];

export const PIPELINE_STAGES: PipelineStage[] = [
  {
    id: "target_identified",
    key: "target_identified",
    name: "Target identified",
    description: "Company or opportunity has been identified.",
    sortOrder: 1,
    color: "bg-slate-100 text-slate-700",
  },
  {
    id: "contact_found",
    key: "contact_found",
    name: "Contact found",
    description: "Useful person or department identified.",
    sortOrder: 2,
    color: "bg-sky-100 text-sky-800",
  },
  {
    id: "first_email_sent",
    key: "first_email_sent",
    name: "First email sent",
    description: "Initial outreach sent manually.",
    sortOrder: 3,
    color: "bg-blue-100 text-blue-800",
  },
  {
    id: "call_attempted",
    key: "call_attempted",
    name: "Call attempted",
    description: "Phone outreach attempted.",
    sortOrder: 4,
    color: "bg-cyan-100 text-cyan-800",
  },
  {
    id: "connected",
    key: "connected",
    name: "Connected",
    description: "Conversation started.",
    sortOrder: 5,
    color: "bg-teal-100 text-teal-800",
  },
  {
    id: "need_confirmed",
    key: "need_confirmed",
    name: "Need confirmed",
    description: "Potential manpower, subcontracting, vendor or project need.",
    sortOrder: 6,
    color: "bg-emerald-100 text-emerald-800",
  },
  {
    id: "documents_requested",
    key: "documents_requested",
    name: "Documents requested",
    description: "Company or vendor documents are being exchanged.",
    sortOrder: 7,
    color: "bg-amber-100 text-amber-800",
  },
  {
    id: "vendor_registration",
    key: "vendor_registration",
    name: "Vendor registration",
    description: "Supplier onboarding or approval is active.",
    sortOrder: 8,
    color: "bg-orange-100 text-orange-800",
  },
  {
    id: "rfq_received",
    key: "rfq_received",
    name: "RFQ received",
    description: "Client requested pricing or formal offer.",
    sortOrder: 9,
    color: "bg-purple-100 text-purple-800",
  },
  {
    id: "offer_sent",
    key: "offer_sent",
    name: "Offer sent",
    description: "Commercial proposal sent.",
    sortOrder: 10,
    color: "bg-indigo-100 text-indigo-800",
  },
  {
    id: "negotiation",
    key: "negotiation",
    name: "Negotiation",
    description: "Commercial, scope or availability details are active.",
    sortOrder: 11,
    color: "bg-fuchsia-100 text-fuchsia-800",
  },
  {
    id: "won",
    key: "won",
    name: "Won",
    description: "Approved client, supplier relationship or project.",
    sortOrder: 12,
    color: "bg-green-100 text-green-800",
    isWon: true,
  },
  {
    id: "lost",
    key: "lost",
    name: "Lost",
    description: "Closed without active next step.",
    sortOrder: 13,
    color: "bg-rose-100 text-rose-800",
    isLost: true,
  },
  {
    id: "nurture",
    key: "nurture",
    name: "Nurture",
    description: "Longer-term relationship follow-up.",
    sortOrder: 14,
    color: "bg-stone-100 text-stone-800",
  },
];

export const DOCUMENT_CHECKLIST_TITLES = [
  "Company registration",
  "VAT number",
  "Insurance certificate",
  "Bank details",
  "Safety policy",
  "Basic HSE manual",
  "Incident reporting procedure",
  "Worker onboarding checklist",
  "Sample timesheet",
  "Sample daily report",
  "Sample crew CV format",
  "List of available roles",
  "Reference project sheet",
  "Anti-corruption statement",
  "GDPR/privacy statement",
  "Subcontractor agreement template",
  "Worker document checklist",
  "A1/posting process description",
  "Accommodation/transport process",
  "Rate card or pricing model",
  "Capability statement",
];
