import { DOCUMENT_CHECKLIST_TITLES, PIPELINE_STAGES } from "@/lib/constants";
import type {
  Activity,
  ChecklistItem,
  Company,
  Contact,
  DocumentRecord,
  Opportunity,
  Task,
  Worker,
} from "@/lib/types";

export const companies: Company[] = [
  {
    id: "company-01",
    name: "AlpenTech MEP GmbH",
    legalName: "AlpenTech MEP GmbH",
    companyType: "mep_contractor",
    status: "contact_found",
    country: "Austria",
    city: "Vienna",
    website: "https://alpentech-mep.example",
    websiteDomain: "alpentech-mep.example",
    linkedinUrl: "https://linkedin.com/company/alpentech-mep",
    sourceUrl: "https://example.com/projects/vienna-dc",
    sectors: ["Data center", "MEP", "Electrical installation"],
    targetCountries: ["Austria", "Germany"],
    priority: "high",
    leadScore: 21,
    leadScoreReason:
      "Active in Austria data-center MEP work and likely to need supervised electrical crews during peak site phases.",
    owner: "Ralph",
    description: "MEP contractor with Austrian industrial and data-center references.",
    currentProjects: "Vienna region data-center package and industrial retrofit work.",
    painPoints:
      "Peak-load electrical installation crews, documentation discipline, German site communication.",
    notes: "Good first outreach target for Ralph.",
    lastContactAt: "2026-04-20",
    nextActionAt: "2026-04-27",
  },
  {
    id: "company-02",
    name: "NordRail Systems AG",
    legalName: "NordRail Systems AG",
    companyType: "rail_oem",
    status: "contacted",
    country: "Germany",
    city: "Munich",
    website: "https://nordrail.example",
    websiteDomain: "nordrail.example",
    sourceUrl: "https://example.com/rail-retrofit-contract",
    sectors: ["Rail / rolling stock", "Electrical installation", "Commissioning"],
    targetCountries: ["Germany", "Austria"],
    priority: "critical",
    leadScore: 23,
    leadScoreReason:
      "Rail retrofit and commissioning work maps directly to Triangle electrical crew and supervisor capability.",
    owner: "Ralph",
    description: "Rolling-stock modernization and rail systems supplier.",
    currentProjects: "Fleet retrofit program with electrical cabinet and cabling scope.",
    painPoints: "Reliable retrofit crews, supervision, travel-ready documentation.",
    lastContactAt: "2026-04-22",
    nextActionAt: "2026-04-25",
  },
  {
    id: "company-03",
    name: "Danube Automation d.o.o.",
    companyType: "automation_integrator",
    status: "target",
    country: "Croatia",
    city: "Zagreb",
    website: "https://danube-automation.example",
    websiteDomain: "danube-automation.example",
    sectors: ["Automation", "Commissioning", "Manufacturing"],
    targetCountries: ["Croatia", "Slovenia", "Hungary"],
    priority: "medium",
    leadScore: 16,
    leadScoreReason: "Good automation relevance, but manpower need needs confirmation.",
    owner: "Nikola",
    description: "Regional automation and PLC integrator.",
    painPoints: "Commissioning support and peak project staffing.",
    nextActionAt: "2026-04-29",
  },
  {
    id: "company-04",
    name: "Baltic Data Center Construction AB",
    companyType: "data_center_contractor",
    status: "research",
    country: "Sweden",
    city: "Stockholm",
    website: "https://bdcc.example",
    websiteDomain: "bdcc.example",
    sectors: ["Data center", "Electrical installation", "Infrastructure"],
    targetCountries: ["Sweden", "Denmark", "Germany"],
    priority: "high",
    leadScore: 19,
    leadScoreReason: "Data-center contractor in target sector; needs contact validation.",
    owner: "Ralph",
    description: "Data-center construction contractor.",
    nextActionAt: "2026-05-02",
  },
  {
    id: "company-05",
    name: "Kovacs Industrial Projects Kft",
    companyType: "industrial_oem",
    status: "replied",
    country: "Hungary",
    city: "Gyor",
    website: "https://kovacs-industrial.example",
    websiteDomain: "kovacs-industrial.example",
    sectors: ["Industrial construction", "Manufacturing", "Electrical installation"],
    targetCountries: ["Hungary", "Austria", "Slovakia"],
    priority: "high",
    leadScore: 20,
    leadScoreReason:
      "Industrial expansion and CEE geography align well with supervised crew offer.",
    owner: "Nikola",
    description: "Industrial project delivery and plant expansion partner.",
    currentProjects: "Plant modernization package.",
    painPoints: "Electrical crew availability and site reporting.",
    lastContactAt: "2026-04-23",
    nextActionAt: "2026-04-28",
  },
];

export const contacts: Contact[] = [
  {
    id: "contact-01",
    companyId: "company-01",
    fullName: "Martin Weber",
    jobTitle: "Electrical Project Manager",
    roleCategory: "project_manager",
    email: "martin.weber@example.com",
    phone: "+43 1 555 0101",
    language: "German",
    country: "Austria",
    priority: "high",
    owner: "Ralph",
    lastContactAt: "2026-04-20",
    nextActionAt: "2026-04-27",
    optOut: false,
    doNotContact: false,
  },
  {
    id: "contact-02",
    companyId: "company-02",
    fullName: "Anna Schuster",
    jobTitle: "Head of Subcontracting",
    roleCategory: "subcontracting",
    email: "anna.schuster@example.com",
    language: "German",
    country: "Germany",
    priority: "critical",
    owner: "Ralph",
    lastContactAt: "2026-04-22",
    nextActionAt: "2026-04-25",
    optOut: false,
    doNotContact: false,
  },
  {
    id: "contact-03",
    companyId: "company-05",
    fullName: "Balazs Nagy",
    jobTitle: "Construction Manager",
    roleCategory: "construction_manager",
    email: "balazs.nagy@example.com",
    language: "English",
    country: "Hungary",
    priority: "high",
    owner: "Nikola",
    lastContactAt: "2026-04-23",
    nextActionAt: "2026-04-28",
    optOut: false,
    doNotContact: false,
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "opp-01",
    companyId: "company-01",
    primaryContactId: "contact-01",
    stageId: "need_confirmed",
    title: "Vienna data-center electrical crew support",
    opportunityType: "data_center_electrical",
    sector: "Data center",
    country: "Austria",
    city: "Vienna",
    estimatedValue: 185000,
    currency: "EUR",
    probability: 45,
    estimatedCrewSize: 8,
    estimatedSupervisors: 1,
    expectedStartDate: "2026-06-03",
    expectedDurationWeeks: 14,
    scopeSummary:
      "Supervised electrical installation crew for cable tray, cabling support and site reporting.",
    clientNeed: "Reliable peak-load crew with documentation discipline.",
    nextStep: "Send capability summary and ask for vendor registration process.",
    owner: "Ralph",
    nextActionAt: "2026-04-27",
    status: "open",
  },
  {
    id: "opp-02",
    companyId: "company-02",
    primaryContactId: "contact-02",
    stageId: "first_email_sent",
    title: "Rail retrofit electrical team intro",
    opportunityType: "rail_retrofit_crew",
    sector: "Rail / rolling stock",
    country: "Germany",
    estimatedValue: 240000,
    currency: "EUR",
    probability: 25,
    estimatedCrewSize: 6,
    expectedStartDate: "2026-07-15",
    expectedDurationWeeks: 20,
    nextStep: "Follow up with short German capability note.",
    owner: "Ralph",
    nextActionAt: "2026-04-25",
    status: "open",
  },
  {
    id: "opp-03",
    companyId: "company-05",
    primaryContactId: "contact-03",
    stageId: "connected",
    title: "Industrial modernization electrical support",
    opportunityType: "industrial_installation",
    sector: "Industrial construction",
    country: "Hungary",
    estimatedValue: 95000,
    currency: "EUR",
    probability: 35,
    estimatedCrewSize: 4,
    expectedStartDate: "2026-05-20",
    nextStep: "Clarify scope and accommodation expectations.",
    owner: "Nikola",
    nextActionAt: "2026-04-28",
    status: "open",
  },
  {
    id: "opp-04",
    companyId: "company-04",
    stageId: "target_identified",
    title: "Nordics data-center contractor research",
    opportunityType: "vendor_registration",
    sector: "Data center",
    country: "Sweden",
    estimatedValue: 0,
    currency: "EUR",
    probability: 10,
    estimatedCrewSize: 10,
    nextStep: "Find electrical package manager or procurement contact.",
    owner: "Ralph",
    nextActionAt: "2026-05-02",
    status: "open",
  },
];

export const tasks: Task[] = [
  {
    id: "task-01",
    title: "Follow up with NordRail after first email",
    assignedTo: "Ralph",
    relatedEntityType: "opportunity",
    relatedEntityId: "opp-02",
    priority: "critical",
    status: "open",
    dueDate: "2026-04-25",
  },
  {
    id: "task-02",
    title: "Prepare vendor document checklist",
    assignedTo: "Nikola",
    relatedEntityType: "company",
    relatedEntityId: "company-01",
    priority: "high",
    status: "in_progress",
    dueDate: "2026-04-26",
  },
  {
    id: "task-03",
    title: "Import next 50 target companies",
    assignedTo: "Nikola",
    relatedEntityType: "none",
    priority: "medium",
    status: "open",
    dueDate: "2026-04-30",
  },
  {
    id: "task-04",
    title: "Find procurement contact at Baltic Data Center Construction",
    assignedTo: "Ralph",
    relatedEntityType: "company",
    relatedEntityId: "company-04",
    priority: "high",
    status: "open",
    dueDate: "2026-05-02",
  },
];

export const activities: Activity[] = [
  {
    id: "activity-01",
    activityType: "import",
    title: "Imported first lead batch",
    summary: "Seed batch of priority companies added for 300-company target.",
    occurredAt: "2026-04-19T10:00:00Z",
    createdBy: "Nikola",
  },
  {
    id: "activity-02",
    activityType: "email",
    title: "First email sent to NordRail",
    summary: "Short German intro sent manually. Follow-up scheduled.",
    companyId: "company-02",
    contactId: "contact-02",
    opportunityId: "opp-02",
    occurredAt: "2026-04-22T08:30:00Z",
    createdBy: "Ralph",
  },
  {
    id: "activity-03",
    activityType: "call",
    title: "Intro call with Kovacs Industrial",
    summary: "Confirmed possible need for 4 electricians and one supervisor.",
    companyId: "company-05",
    contactId: "contact-03",
    opportunityId: "opp-03",
    occurredAt: "2026-04-23T12:15:00Z",
    createdBy: "Nikola",
  },
  {
    id: "activity-04",
    activityType: "ai_generation",
    title: "Lead scores generated",
    summary: "AI scoring prepared for priority Austria/Germany leads.",
    occurredAt: "2026-04-23T16:10:00Z",
    createdBy: "Nikola",
  },
];

export const documents: DocumentRecord[] = [
  {
    id: "doc-01",
    title: "Triangle Services capability statement",
    documentCategory: "capability_statement",
    fileName: "triangle-capability-statement.pdf",
    fileExtension: "pdf",
    version: 1,
    visibility: "internal",
    sensitivity: "normal",
    reviewDate: "2026-05-15",
    uploadedBy: "Nikola",
    uploadedAt: "2026-04-21",
  },
  {
    id: "doc-02",
    title: "Company registration",
    documentCategory: "company_registration",
    fileName: "company-registration.pdf",
    fileExtension: "pdf",
    version: 1,
    visibility: "partner_only",
    sensitivity: "legal",
    reviewDate: "2026-06-01",
    uploadedBy: "Nikola",
    uploadedAt: "2026-04-21",
  },
  {
    id: "doc-03",
    title: "Insurance certificate",
    documentCategory: "insurance_certificate",
    fileName: "insurance-certificate.pdf",
    fileExtension: "pdf",
    version: 1,
    visibility: "partner_only",
    sensitivity: "confidential",
    expiryDate: "2026-12-31",
    reviewDate: "2026-11-30",
    uploadedBy: "Nikola",
    uploadedAt: "2026-04-21",
  },
];

export const checklist: ChecklistItem[] = DOCUMENT_CHECKLIST_TITLES.map((title, index) => ({
  id: `checklist-${index + 1}`,
  title,
  category:
    index < 4
      ? "Company documents"
      : index < 8
        ? "Compliance / Safety"
        : index < 11
          ? "Worker documents"
          : index < 18
            ? "Sales documents"
            : "Project documents",
  status:
    title === "Company registration" ||
    title === "Insurance certificate" ||
    title === "Capability statement"
      ? "uploaded"
      : title === "Safety policy" || title === "Basic HSE manual"
        ? "draft"
        : "missing",
  owner: index % 2 === 0 ? "Nikola" : "Ralph",
  reviewDate: index % 3 === 0 ? "2026-05-15" : undefined,
  linkedDocumentId:
    title === "Company registration"
      ? "doc-02"
      : title === "Insurance certificate"
        ? "doc-03"
        : title === "Capability statement"
          ? "doc-01"
          : undefined,
}));

export const workers: Worker[] = [
  {
    id: "worker-01",
    fullName: "Ivan Horvat",
    role: "electrical_supervisor",
    workerType: "freelancer",
    email: "ivan.horvat@example.com",
    country: "Croatia",
    city: "Zagreb",
    languages: ["Croatian", "English", "German"],
    skills: ["Site supervision", "Cable tray", "Daily reporting"],
    certificates: ["VCA", "A1 possible"],
    industries: ["Data center", "Industrial construction"],
    availabilityStatus: "available_soon",
    availableFrom: "2026-05-10",
    preferredCountries: ["Austria", "Germany"],
    dailyRateExpectation: 320,
    currency: "EUR",
    reliabilityScore: 5,
    qualityScore: 5,
    safetyScore: 4,
    hasA1Possible: true,
    hasOwnTools: true,
    hasCar: true,
    status: "active",
  },
  {
    id: "worker-02",
    fullName: "Matej Kralj",
    role: "plc_engineer",
    workerType: "subcontractor",
    country: "Slovenia",
    city: "Maribor",
    languages: ["Slovenian", "English", "German"],
    skills: ["Siemens PLC", "Commissioning", "Troubleshooting"],
    certificates: ["S7", "TIA Portal"],
    industries: ["Automation", "Manufacturing"],
    availabilityStatus: "busy",
    preferredCountries: ["Austria", "Slovenia", "Germany"],
    dailyRateExpectation: 520,
    currency: "EUR",
    reliabilityScore: 4,
    qualityScore: 5,
    safetyScore: 4,
    hasA1Possible: true,
    hasOwnTools: false,
    hasCar: true,
    status: "active",
  },
  {
    id: "worker-03",
    fullName: "Petar Novak",
    role: "cable_tray_installer",
    workerType: "employee_candidate",
    country: "Croatia",
    city: "Osijek",
    languages: ["Croatian", "English"],
    skills: ["Cable tray", "Cable pulling", "Industrial sites"],
    certificates: ["Basic safety"],
    industries: ["Electrical installation", "Industrial construction"],
    availabilityStatus: "available",
    preferredCountries: ["Austria", "Germany", "Croatia"],
    hourlyRateExpectation: 24,
    currency: "EUR",
    reliabilityScore: 3,
    qualityScore: 4,
    safetyScore: 4,
    hasA1Possible: false,
    hasOwnTools: true,
    hasCar: false,
    status: "candidate",
  },
];

export const pipelineStages = PIPELINE_STAGES;
